src/Entity/DvdAbstract.php
<?php

declare(strict_types=1);

/**
 * This file is part of Black Org.
 *
 * Black Org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Black Org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see
 * <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Abstract class for real entity and pending entities.
 */
class DvdAbstract implements \Stringable
{
    /**
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    protected ?int $id = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 2)]
    #[Assert\Range(min: 1, max: 99)]
    protected ?int $part = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 2)]
    #[Assert\Range(min: 1, max: 99)]
    protected ?int $number = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 5)]
    #[Assert\Range(min: 1, max: 99999)]
    protected ?int $price = null;

    /**
     * @var bool|null
     */
    #[ORM\Column(type: 'boolean', nullable: false)]
    protected ?bool $ttc = null;

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'string', length: 15, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 15)]
    protected ?string $ref = null;

    /**
     * @var DateTime|null
     */
    #[ORM\Column(type: 'date', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Type('\DateTime')]
    protected ?DateTime $date = null;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int|null
     */
    public function getPart(): ?int
    {
        return $this->part;
    }

    /**
     * @return Dvd
     */
    public function setPart(?int $part): self
    {
        $this->part = $part;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return (string) $this->getDisplayName();
    }

    /**
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return 'Part ' . $this->part . ' — Vol ' . $this->number;
    }

    /**
     * @return string|null
     */
    public function getDisplayNumber(): ?string
    {
        return $this->part . '-' . $this->number;
    }

    /**
     * @return int|null
     */
    public function getNumber(): ?int
    {
        return $this->number;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function isTTC(): ?bool
    {
        return $this->ttc;
    }

    /**
     * @param bool $ttc
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setTTC(?bool $ttc): self
    {
        $this->ttc = $ttc;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getRef(): ?string
    {
        return $this->ref;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setRef(?string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    /**
     * @return DateTime|null
     */
    public function getDate(): ?DateTime
    {
        return $this->date;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setDate(?DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Controller/AnimeController.php
<?php

declare(strict_types=1);

/**
 * This file is part of Black Org.
 *
 * Black Org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Black Org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see
 * <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Controller;

use App\Entity\CaseEntity;
use App\Entity\Dvd;
use App\Entity\Episode;
use App\Entity\Track;
use App\Twig\AppExtension;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Exception;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class AnimeController.
 */
class AnimeController extends AbstractController
{
    /**
     * Episodes page controller.
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    #[Route("/episodes", name: "episodes", methods: ["GET"])]
    public function indexAction(EntityManagerInterface $entityManager, TranslatorInterface $translator): Response
    {
        $episodes = $entityManager->getRepository(Episode::class)->getLatestEpisodes(15);

        if (!(is_countable($episodes) ? count($episodes) : 0)) {
            throw new HttpException(404, 'Aucun épisode n’a été trouvé. ' . $translator->trans('TempAbortMsg'));
        }

        $latestEpisode = $entityManager->getRepository(Episode::class)->getLatestEpisode();

        return $this->render('anime/episodes.html.twig', [
            'breadcrumb' => [$this->generateUrl('anime') => 'Anime'],
            'episodes' => $episodes,
            'nbEpisodes' => $latestEpisode->getNumber(),
        ]);
    }

    /**
     * Episodes page controller.
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     * @throws Exception
     */
    #[Route("/episodes/page/{page<[1-9]\d*>}", name: "episodes_paginated", methods: ["GET"])]
    public function episodesPageAction(EntityManagerInterface $entityManager, int $page): Response
    {
        $episodes = $entityManager->getRepository(Episode::class)->getEpisodes($page);

        if (!(is_countable($episodes['results']) ? count($episodes['results']) : 0)) {
            throw new HttpException(404, 'Cette page n’existe pas. Revenir à la <a href="' . $this->generateUrl('episodes') . '">liste des épisodes</a>.');
        }
        $latestEpisode = $entityManager->getRepository(Episode::class)->getLatestEpisode();

        return $this->render('anime/episodes-page.html.twig', [
            'breadcrumb' => [
                $this->generateUrl('anime') => 'Anime',
                $this->generateUrl('episodes') => 'Épisodes',
            ],
            'episodes' => $episodes,
            'nbEpisodes' => $latestEpisode->getNumber(),
        ]);
    }

    /**
     * Season view page controller.
     *
     * @deprecated
     */
    #[Route("/episodes/season/{season<[1-9]\d*>}", name: "episodes_season", methods: ["GET"])]
    public function seasonViewAction(EntityManagerInterface $entityManager, int $season): Response
    {
        $ep = $entityManager->getRepository(Episode::class)->findOneBy(['season' => $season], ['number' => 'ASC']);
        if (null !== $ep) {
            return $this->redirectToRoute('episodes_paginated', ['page' => ceil($ep->getNumber() / Episode::NUM_ITEMS)], 301);
        } else {
            throw new HttpException(404, 'Cette page n’existe pas. Revenir à la <a href="' . $this->generateUrl('episodes') . '">liste des épisodes</a>.');
        }
    }

    /**
     * Episode view page controller.
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    #[Route("/episodes/{number<[1-9]\d*>}", name: "episode_view", methods: ["GET"])]
    public function episodeViewAction(EntityManagerInterface $entityManager, AppExtension $appExtension, Episode $episode): Response
    {
        $epBefore = $entityManager->getRepository(Episode::class)->findOneBy(['number' => $episode->getNumber() - 1]);
        $epAfter = $entityManager->getRepository(Episode::class)->findOneBy(['number' => $episode->getNumber() + 1]);

        $latestEpisode = $entityManager->getRepository(Episode::class)->getLatestEpisode();
        $page = ceil($episode->getNumber() / Episode::NUM_ITEMS);
        $firstEpisodeNumber = $appExtension->addLeadingZero(((($page - 1) * Episode::NUM_ITEMS) + 1), 3);
        $lastEpisodeNumber = $appExtension->addLeadingZero((($page * Episode::NUM_ITEMS > $latestEpisode->getNumber()) ? $latestEpisode->getNumber() : $page * Episode::NUM_ITEMS), 3);

        $breadcrumb = [
            $this->generateUrl('anime') => 'Anime',
            $this->generateUrl('episodes') => 'Épisodes',
            $this->generateUrl('episodes_paginated', ['page' => $page]) => 'Épisodes ' . $firstEpisodeNumber . ' - ' . $lastEpisodeNumber,
        ];

        return $this->render('anime/episode-view.html.twig', [
            'shortTitle' => 'Épisode ' . $episode->getDisplayNumber(),
            'breadcrumb' => $breadcrumb,
            'episode' => $episode,
            'epBefore' => $epBefore,
            'epAfter' => $epAfter,
        ]);
    }

    /**
     * Movie page controller.
     */
    #[Route("/movies", name: "movies", methods: ["GET"])]
    public function moviesAction(EntityManagerInterface $entityManager): Response
    {
        $movies = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'movie'], ['date' => 'ASC']);
        $special_movies = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'movie_special'], ['date' => 'ASC']);

        return $this->render('anime/movies.html.twig', [
            'breadcrumb' => [$this->generateUrl('anime') => 'Anime'],
            'movies' => $movies,
            'special_movies' => $special_movies,
        ]);
    }

    /**
     * Featured movie view page controller.
     */
    #[Route("/movies/{number<[1-9]\d*>}", name: "movie_view", methods: ["GET"])]
    public function featuredMovieViewAction(EntityManagerInterface $entityManager, #[MapEntity(expr: "repository.findMovie(number)")] CaseEntity $movie): Response
    {
        return $this->movieViewAction($entityManager, $movie);
    }

    /**
     * Movie view page controller.
     */
    private function movieViewAction(EntityManagerInterface $entityManager, CaseEntity $movie): Response
    {
        $movieBefore = $entityManager->getRepository(CaseEntity::class)->findOneBy(['number' => $movie->getNumber() - 1, 'type' => $movie->getType()]);
        $movieAfter = $entityManager->getRepository(CaseEntity::class)->findOneBy(['number' => $movie->getNumber() + 1, 'type' => $movie->getType()]);
        if ('movie' == $movie->getType()) {
            $ending = $entityManager->getRepository(Track::class)->findMovieEnding($movie->getNumber());
        } else {
            $ending = null;
        }

        $breadcrumb = [$this->generateUrl('anime') => 'Anime'];
        if ('movie' === $movie->getType()) {
            $breadcrumb[$this->generateUrl('movies') . '#featuredmovies'] = 'Films';
        } elseif ('movie_special' === $movie->getType()) {
            $breadcrumb[$this->generateUrl('movies') . '#specialmovies'] = 'Films spéciaux';
        }

        return $this->render('anime/movie-view.html.twig', [
            'breadcrumb' => $breadcrumb,
            'movie' => $movie,
            'movieBefore' => $movieBefore,
            'movieAfter' => $movieAfter,
            'ending' => $ending,
        ]);
    }

    /**
     * Special movie view page controller.
     */
    #[Route("/movies/{number<[1-9]\d*>}sp", name: "movie_special_view", methods: ["GET"])]
    public function specialMovieViewAction(EntityManagerInterface $entityManager, #[MapEntity(expr: "repository.findSpecialMovie(number)")] CaseEntity $special_movie): Response
    {
        return $this->movieViewAction($entityManager, $special_movie);
    }

    /**
     * Special page controller.
     */
    #[Route("/specials", name: "specials", methods: ["GET"])]
    public function specialsAction(EntityManagerInterface $entityManager): Response
    {
        $ovas = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'ova'], ['date' => 'ASC']);
        $magic_files = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'magic_file'], ['date' => 'ASC']);
        $dc_specials = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'dc_special'], ['date' => 'ASC']);
        $mk_specials = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'mk_special'], ['date' => 'ASC']);
        $mk1412_episodes = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'mk1412'], ['date' => 'ASC']);
        $tanpenshus = $entityManager->getRepository(CaseEntity::class)->findBy(['type' => 'tanpenshu'], ['date' => 'ASC']);

        return $this->render('anime/specials.html.twig', [
            'breadcrumb' => [$this->generateUrl('anime') => 'Anime'],
            'ovas' => $ovas,
            'magic_files' => $magic_files,
            'dc_specials' => $dc_specials,
            'mk_specials' => $mk_specials,
            'mk1412_episodes' => $mk1412_episodes,
            'tanpenshus' => $tanpenshus,
        ]);
    }

    /**

templates/anime/dvds.html.twig
{% extends "base.html.twig" %}

{% block title %}DVD{% endblock %}
{% block content %}
    <p>Les numéros d’épisodes sont donnés à titre indicatif, il arrive que certains épisodes soient répartis sur d’autres DVD pour empêcher des épisodes consécutifs d’être séparés sur plusieurs DVD.</p>
    {% for row in dvds|batch(4, 'Empty space') %}
        <div class="row">
            {% for part, dvd in row %}
                <div class="col-sm-6 col-lg-3 mb-3">
                    {% if dvd != 'Empty space' %}
                        <div class="card">
                            <div class="card-header">
                                <span class="card-title"><a href="{{ path('dvd_view', {'part': part}) }}">Part {{ part }}</a></span>
                            </div>
                            <div class="card-body">
                                {% if (dvd[0].episodes)|length and (dvd[dvd|length - 1].episodes)|length %}
                                    Épisodes {{ dvd[0].episodes[0].number|add_leading_zero(3) }} à {{ dvd[dvd|length - 1].episodes[dvd[dvd|length - 1].episodes|length - 1].number|add_leading_zero(3) }}
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
    <p class="text-center"><a href="{{ path('admin_submission_add', {'section': 'dvds'}) }}" class="btn btn-primary">Ajouter un DVD</a></p>
{% endblock %}

templates/anime/episode-view.html.twig
{% extends "base.html.twig" %}

{% block title %}Épisode {{ episode.number|add_leading_zero(3) }} — {{ episode.titleFr }}{% if episode.part != 0 %} (Partie {{ episode.part }}{% if episode.partTitle is not null and episode.partTitle is not empty %} — {{ episode.partTitle }}{% endif %}){% endif %}{% endblock %}
{% block content %}
    {% set imgFilename = '/img/episode/' ~ episode.number|add_leading_zero(3) ~ '.jpg' %}
    {% if not file_exists('../public' ~ imgFilename) %}
        {% set imgFilename = '/img/unaired.jpg' %}
    {% endif %}
    <div class="row">
        <div class="col-md-8 order-2 order-md-1">
            <h3>{{ episode.titleFr }}{% if episode.part != 0 %} (Partie {{ episode.part }}{% if episode.partTitle is not null and episode.partTitle is not empty %} — {{ episode.partTitle }}{% endif %}){% endif %}</h3>
            {% if episode.summary is not null and episode.summary is not empty %}
                <h4>Synopsis</h4>

                {{ episode.summary|markdown_to_html }}
            {% endif %}

            {% for case in episode.cases %}
                <h4><a href="{{ get_case_path(case) }}">{{ case.displayName }}</a></h4>
            {% endfor %}
        </div>
        <div class="col-md-4 order-1 order-md-2">
            <div class="table-responsive">
                <table class="table profile_table episode">
                    <thead>
                        <tr class="caption">
                            <th colspan="2">Épisode {{ episode.number|add_leading_zero(3) }} <a href="{{ path('admin_submission_edit', {'section': 'episodes', 'id': episode.id }) }}"><i class="far fa-edit text-white"></i></a></th>
                        </tr>
                        <tr>
                            <th class="p-0 text-center" colspan="2">
                                <a href="{{ asset(imgFilename) }}">
                                    <img class="img-fluid" src="{{ asset(imgFilename) }}" alt="" />
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="caption">
                            <th colspan="2">Informations</th>
                        </tr>
                        <tr>
                            <th>Titre français</th>
                            <td>{{ episode.titleFr }}</td>
                        </tr>
                        <tr>
                            <th>Titre original</th>
                            <td>{% if episode.titleJpKanji %}{{ episode.titleJpKanji|rubify }}<br />({% endif %}<em>{{ episode.titleJpRomaji|rubify }}</em>{% if episode.titleJpKanji %}){% endif %}</td>
                        </tr>
                        <tr>
                            <th>Partie</th>
                            <td>{% if episode.part != 0 %}{{ episode.part }}{% if episode.partTitle is not null and episode.partTitle is not empty %} — {{ episode.partTitle }}{% endif %}{% else %}Unique{% endif %}</td>
                        </tr>
                        {% if episode.special %}
                            <tr>
                                <th>Épisode spécial</th>
                                <td>Oui</td>
                            </tr>
                        {% endif %}
                        <tr class="caption">
                            <th colspan="2">Adaptation</th>
                        </tr>
                        {% if episode.cases|length %}
                            <tr>
                                <th>Affaire{% if episode.cases|length > 1 %}s{% endif %}</th>
                                <td>
                                    {% for case in episode.cases %}
                                        {% if loop.index > 1 %}<br />{% endif %}
                                        <a href="{{ get_case_path(case) }}">{{ case.displayName('long') }}</a>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}

                        {% if episode.cases|length %}
                            <tr>
                                <th>Manga</th>
                                <td>
                                    {% for case in episode.cases %}
                                        {% if loop.index > 1 %}<br />{% endif %}
                                        {% if case.chapters|length %}
                                            {% include 'helper/manga-source.html.twig' with { 'from': case.chapters[0], 'to': case.chapters[(case.chapters|length - 1)] } only %}
                                        {% else %}
                                            Hors Série
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        <tr class="caption">
                            <th colspan="2">Diffusion</th>
                        </tr>
                        <tr>
                            <th>Saison</th>
                            <td>{{ episode.season }}</td>
                        </tr>
                        <tr>
                            <th>Date de diffusion</th>
                            <td>{{ episode.date|format_date('long') }}</a></td>
                        </tr>
                        {% if episode.dateRemastered is not null %}
                            <tr>
                                <th>Date de remasterisation</th>
                                <td>{{ episode.dateRemastered|format_date('long') }}</td>
                            </tr>
                        {% endif %}
                        {% if episode.rating is not null %}
                            <tr>
                                <th>Audience</th>
                                <td>{{ episode.rating|format_number(style='decimal') }}&#8239;%</td>{# not formatted as percent as it truncates decimals ¬_¬ #}
                            </tr>
                        {% endif %}
                        <tr>
                            <th>Indice</th>
                            <td>{{ episode.nextHint }}</td>
                        </tr>
                        {% if episode.dvd is not null %}
                            <tr>
                                <th>DVD</th>
                                <td><a href="{{ get_dvd_path(episode.dvd) }}">Part {{ episode.dvd.part }} — Vol {{ episode.dvd.number }}</a></td>
                            </tr>
                        {% endif %}
                        {% if episode.opening is not null or episode.ending is not null %}
                            <tr class="caption">
                                <th colspan="2">Musique</th>
                            </tr>
                            {% if episode.opening is not null %}
                                <tr>
                                    <th>Opening</th>
                                    <td>{{ episode.opening.number }} — {{ episode.opening.titleJp }} — {{ episode.opening.artist }}</td>
                                </tr>
                            {% endif %}
                            {% if episode.ending is not null %}
                                <tr>
                                    <th>Ending</th>
                                    <td>{{ episode.ending.number }} — {{ episode.ending.titleJp }} — {{ episode.ending.artist }}</td>
                                </tr>
                            {% endif %}
                        {% endif %}
                        <tr class="caption">
                            <th colspan="2">Liens</th>
                        </tr>
                        <tr>
                            <th>Téléchargement</th>
                            <td><a rel="nofollow" href="https://detective-conan-vostfr.info/rechercher.php?typesEpisode=1&amp;equipes=0&amp;numero={{ episode.number|add_leading_zero(3) }}&amp;contenus=0&amp;dateSortie=0&amp;tri=dateD">Meitantei Canon</a></td>
                        </tr>
                        {% if episode.ADNId is not null and episode.ADNId != 0 %}
                            <tr>
                                <th>Streaming</th>
                                <td><a rel="nofollow" href="https://animedigitalnetwork.fr/video/detective-conan/{{ episode.ADNId }}">Anime Digital Network</a></td>
                            </tr>
                        {% endif %}
                        <tr class="caption">
                            <th colspan="2">Chronologie</th>
                        </tr>
                        {% if epBefore is not null %}
                            <tr>
                                <th>Épisode précédent</th>
                                <td><a href="{{ get_episode_path(epBefore) }}">&lt;&lt; {{ epBefore.number|add_leading_zero(3) }} — {{ epBefore.titleFr }}{% if epBefore.part != 0 %} (Partie {{ epBefore.part }}{% if epBefore.partTitle is not null and epBefore.partTitle is not empty %} — {{ epBefore.partTitle }}{% endif %}){% endif %}</a></td>
                            </tr>
                        {% endif %}

                        {% if epAfter is not null %}
                            <tr>
                                <th>Épisode suivant</th>
                                <td><a href="{{ get_episode_path(epAfter) }}">{{ epAfter.number|add_leading_zero(3) }} — {{ epAfter.titleFr }}{% if epAfter.part != 0 %} (Partie {{ epAfter.part }}{% if epAfter.partTitle is not null and epAfter.partTitle is not empty %} — {{ epAfter.partTitle }}{% endif %}){% endif %} &gt;&gt;</a></td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td colspan="2" class="text-center"><a href="{{ path('episodes') }}">Revenir à la liste des épisodes</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/anime/episodes-page.html.twig
{% extends "base.html.twig" %}

{% block title %}Épisodes {{ (episodes.results|first).number|add_leading_zero(3) }} - {{ (episodes.results|last).number|add_leading_zero(3) }}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{  encore_entry_script_tags('season-view') }}
{% endblock %}

{% block content %}
    {{ include('helper/episodes-page-switch.html.twig') }}
    <div class="table-responsive">
        <table class="table table-episodes">
            <thead>
                <tr>
                    <th class="text-center d-none d-md-table-cell">Image</th>
                    <th class="text-center d-none d-sm-table-cell">#</th>
                    <th>Titre</th>
                    <th class="text-center d-none d-md-table-cell">Affaire</th>
                    <th class="text-center">Source</th>
                    <th class="text-center">Diffusion</th>
                </tr>
            </thead>
            <tbody>
                {% for episode in episodes.results %}
                    {% set imgFilename = '/img/episode/' ~ episode.number|add_leading_zero(3) ~ '_small.jpg' %}
                    {% if not file_exists('../public' ~ imgFilename) %}
                        {% set imgFilename = '/img/unaired_small.jpg' %}
                    {% endif %}
                    <tr id="ep{{ episode.number|add_leading_zero(3) }}"{% if episode.special %} class="table-primary"{% endif %}>
                        <td class="align-middle text-center p-0 d-none d-md-table-cell"><img src="{{ asset(imgFilename) }}" alt="" /></td>
                        <td class="align-middle text-center pt-0 pb-0 d-none d-sm-table-cell"><strong>{{ episode.number|add_leading_zero(3) }}</strong> <a href="{{ path('admin_submission_edit', {'section': 'episodes', 'id': episode.id}) }}"><i class="far fa-edit"></i></a>{% if episode.number <= 906 %} <a rel="nofollow" href="https://detective-conan-vostfr.info/rechercher.php?typesEpisode=1&amp;equipes=0&amp;numero={{ episode.number|add_leading_zero(3) }}&amp;contenus=0&amp;dateSortie=0&amp;tri=dateD"><i class="fas fa-download"></i></a>{% endif %}{% if episode.ADNId is not null and episode.ADNId != 0 %} <a rel="nofollow" href="https://animedigitalnetwork.fr/video/detective-conan/{{ episode.ADNId }}"><i class="fas fa-video"></i></a>{% endif %}</td>
                        <td class="align-middle"><span class="d-sm-none"><a href="{{ path('admin_submission_edit', {'section': 'episodes', 'id': episode.id}) }}"><i class="far fa-edit"></i></a> <strong>{{ episode.number|add_leading_zero(3) }}</strong> — </span><a href="{{ get_episode_path(episode) }}"><strong>{{ episode.titleFr }}</strong></a>{% if episode.part != 0 %} (Partie {{ episode.part }}{% if episode.partTitle is not null and episode.partTitle is not empty %} — {{ episode.partTitle }}{% endif %}){% endif %}
                            <p class="d-none d-md-block">{% if episode.titleJpKanji %}<span data-bs-toggle="tooltip" title="{{ episode.titleJpRomaji }}">{{ episode.titleJpKanji|rubify }}</span>{% else %}<em>{{ episode.titleJpRomaji }}</em>{% endif %}</p></td>
                        <td class="align-middle text-center d-none d-md-table-cell">
                            {% if episode.cases|length %}
                                {% for case in episode.cases %}
                                    {% if loop.index > 1 %}<br />{% endif %}
                                    <a href="{{ get_case_path(case) }}">{{ case.displayName('long') }}</a>
                                {% endfor %}
                            {% else %}
                                &nbsp;
                            {% endif %}
                        </td>
                        <td class="align-middle text-center">
                            {% if episode.cases|length %}
                                {% for case in episode.cases %}
                                    {% if loop.index > 1 %}<br />{% endif %}
                                    {% if case.chapters|length %}
                                        {% include 'helper/manga-source.html.twig' with { 'from': case.chapters[0], 'to': case.chapters[(case.chapters|length - 1)] } only %}
                                    {% else %}
                                        <span class="d-none d-md-inline">Hors Série</span>
                                        <a class="d-md-none" href="{{ get_case_path(case) }}">Hors Série n° {{ case.displayNumber }}</a>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                Hors Série
                            {% endif %}
                        </td>
                        <td class="align-middle text-center">{{ episode.date|format_date('medium') }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {{ include('helper/episodes-page-switch.html.twig') }}
{% endblock %}