src/Entity/Character.php
<?php

declare (strict_types=1);

/**
 * This file is part of Black Org.
 *
 * Black Org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Black Org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see
 * <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use ApiPlatform\Metadata\ApiFilter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ApiResource(operations: [new Get(), new GetCollection()])]
#[ApiFilter(filterClass: PropertyFilter::class)]
#[ApiResource(uriTemplate: '/cases/{id}/characters.{_format}', uriVariables: ['id' => new Link(fromClass: \App\Entity\CaseEntity::class, identifiers: ['id'], fromProperty: 'characters')], status: 200, filters: ['annotated_app_entity_character_api_platform_serializer_filter_property_filter'], operations: [new GetCollection()])]
#[ApiResource(uriTemplate: '/character_categories/{id}/characters.{_format}', uriVariables: ['id' => new Link(fromClass: \App\Entity\CharacterCategory::class, identifiers: ['id'], toProperty: 'character_category')], status: 200, filters: ['annotated_app_entity_character_api_platform_serializer_filter_property_filter'], operations: [new GetCollection()])]
#[ORM\Table(name: 'characters', options: ['collate' => 'utf8mb4_general_ci', 'charset' => 'utf8mb4'])]
#[ORM\Entity(repositoryClass: \App\Repository\CharacterRepository::class)]
class Character extends CharacterAbstract implements SubmittableEntityInterface
{
    use SubmittableEntityTrait;
    /**
     * @var CharacterCategory|null
     */
    #[ORM\ManyToOne(targetEntity: 'CharacterCategory', inversedBy: 'characters')]
    #[ORM\JoinColumn(name: 'charactercategory_id', referencedColumnName: 'id', nullable: false)]
    #[Assert\NotBlank]
    protected ?CharacterCategory $character_category = null;
    /**
     * @var CaseEntity|null
     */
    #[ORM\ManyToOne(targetEntity: 'CaseEntity', inversedBy: 'first_appearances')]
    #[ORM\JoinColumn(nullable: true)]
    protected ?CaseEntity $first_appearance = null;
    /**
     * @var \Collection
     */
    #[ORM\ManyToMany(targetEntity: 'CaseEntity', mappedBy: 'characters')]
    protected $cases;
    /**
     * @var \Collection
     */
    #[ORM\JoinTable(name: 'characters_gadgets')]
    #[ORM\ManyToMany(targetEntity: 'Gadget', inversedBy: 'used_by')]
    protected $gadgets;
    /**
     * @var Collection
     */
    #[ORM\OneToMany(targetEntity: 'Gadget', mappedBy: 'created_by')]
    protected $gadgets_invented;
    /**
     * Character constructor.
     */
    public function __construct()
    {
        $this->cases = new ArrayCollection();
        $this->gadgets = new ArrayCollection();
        $this->gadgets_invented = new ArrayCollection();
    }
    public function getFirstAppearance() : ?CaseEntity
    {
        return $this->first_appearance;
    }
    public function setFirstAppearance(?CaseEntity $first_appearance) : self
    {
        $this->first_appearance = $first_appearance;
        return $this;
    }
    public function getCases() : Collection
    {
        return $this->cases;
    }
    public function getGadgetsInvented() : Collection
    {
        return $this->gadgets_invented;
    }
    public function addCase(CaseEntity $case) : self
    {
        $this->cases[] = $case;
        return $this;
    }
    public function removeCase(CaseEntity $case) : self
    {
        $this->cases->removeElement($case);
        return $this;
    }
    public function getGadgets() : Collection
    {
        return $this->gadgets;
    }
    public function addGadget(Gadget $gadget) : self
    {
        $this->gadgets[] = $gadget;
        return $this;
    }
    public function removeGadget(Gadget $gadget) : self
    {
        $this->gadgets->removeElement($gadget);
        return $this;
    }
    public function getCharacterCategory() : ?CharacterCategory
    {
        return $this->character_category;
    }
    public function setCharacterCategory(CharacterCategory $character_category) : self
    {
        $this->character_category = $character_category;
        return $this;
    }
}

src/Entity/DvdAbstract.php
<?php

declare(strict_types=1);

/**
 * This file is part of Black Org.
 *
 * Black Org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Black Org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see
 * <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Abstract class for real entity and pending entities.
 */
class DvdAbstract implements \Stringable
{
    /**
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue]
    protected ?int $id = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 2)]
    #[Assert\Range(min: 1, max: 99)]
    protected ?int $part = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 2)]
    #[Assert\Range(min: 1, max: 99)]
    protected ?int $number = null;

    /**
     * @var int|null
     */
    #[ORM\Column(type: 'integer', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 5)]
    #[Assert\Range(min: 1, max: 99999)]
    protected ?int $price = null;

    /**
     * @var bool|null
     */
    #[ORM\Column(type: 'boolean', nullable: false)]
    protected ?bool $ttc = null;

    /**
     * @var string|null
     */
    #[ORM\Column(type: 'string', length: 15, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 15)]
    protected ?string $ref = null;

    /**
     * @var DateTime|null
     */
    #[ORM\Column(type: 'date', nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Type('\DateTime')]
    protected ?DateTime $date = null;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int|null
     */
    public function getPart(): ?int
    {
        return $this->part;
    }

    /**
     * @return Dvd
     */
    public function setPart(?int $part): self
    {
        $this->part = $part;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return (string) $this->getDisplayName();
    }

    /**
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return 'Part ' . $this->part . ' — Vol ' . $this->number;
    }

    /**
     * @return string|null
     */
    public function getDisplayNumber(): ?string
    {
        return $this->part . '-' . $this->number;
    }

    /**
     * @return int|null
     */
    public function getNumber(): ?int
    {
        return $this->number;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function isTTC(): ?bool
    {
        return $this->ttc;
    }

    /**
     * @param bool $ttc
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setTTC(?bool $ttc): self
    {
        $this->ttc = $ttc;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getRef(): ?string
    {
        return $this->ref;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setRef(?string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    /**
     * @return DateTime|null
     */
    public function getDate(): ?DateTime
    {
        return $this->date;
    }

    /**
     * @return DvdAbstract
     * @return DvdAbstract
     */
    public function setDate(?DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Entity/Gadget.php
<?php

declare (strict_types=1);

/**
 * This file is part of Black Org.
 *
 * Black Org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Black Org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see
 * <https://www.gnu.org/licenses/agpl-3.0.html>.
 */

namespace App\Entity;

use ApiPlatform\Metadata\Link;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Serializer\Filter\PropertyFilter;
use ApiPlatform\Metadata\ApiFilter;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ApiResource(operations: [new Get(), new GetCollection()])]
#[ApiFilter(filterClass: PropertyFilter::class)]
#[ApiResource(uriTemplate: '/cases/{id}/gadgets.{_format}', uriVariables: ['id' => new Link(fromClass: \App\Entity\CaseEntity::class, identifiers: ['id'], fromProperty: 'gadgets')], status: 200, filters: ['annotated_app_entity_gadget_api_platform_serializer_filter_property_filter'], operations: [new GetCollection()])]
#[ApiResource(uriTemplate: '/characters/{id}/gadgets.{_format}', uriVariables: ['id' => new Link(fromClass: \App\Entity\Character::class, identifiers: ['id'], fromProperty: 'gadgets')], status: 200, filters: ['annotated_app_entity_gadget_api_platform_serializer_filter_property_filter'], operations: [new GetCollection()])]
#[ORM\Table(name: 'gadgets', options: ['collate' => 'utf8mb4_general_ci', 'charset' => 'utf8mb4'])]
#[ORM\Entity(repositoryClass: \App\Repository\GadgetRepository::class)]
class Gadget extends GadgetAbstract implements SubmittableEntityInterface
{
    use SubmittableEntityTrait;
    /**
     * @var CaseEntity|null
     */
    #[ORM\ManyToOne(targetEntity: 'CaseEntity', inversedBy: 'first_uses')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    protected ?CaseEntity $first_use = null;
    /**
     * @var Character|null
     */
    #[ORM\ManyToOne(targetEntity: 'Character', inversedBy: 'gadgets_invented')]
    #[ORM\JoinColumn(nullable: true)]
    protected ?Character $created_by = null;
    /**
     * @var Collection
     */
    #[ORM\ManyToMany(targetEntity: 'Character', mappedBy: 'gadgets')]
    protected $used_by;
    /**
     * @var \Collection
     */
    #[ORM\ManyToMany(targetEntity: 'CaseEntity', mappedBy: 'gadgets')]
    protected $cases;
    /**
     * Gadget constructor.
     */
    public function __construct()
    {
        $this->used_by = new ArrayCollection();
        $this->cases = new ArrayCollection();
    }
    public function getFirstUse() : ?CaseEntity
    {
        return $this->first_use;
    }
    public function setFirstUse(?CaseEntity $first_use) : self
    {
        $this->first_use = $first_use;
        return $this;
    }
    public function getCreatedBy() : ?Character
    {
        return $this->created_by;
    }
    public function setCreatedBy(?Character $created_by) : self
    {
        $this->created_by = $created_by;
        return $this;
    }
    public function getUsedBy() : Collection
    {
        return $this->used_by;
    }
    public function addUsedBy(Character $character) : self
    {
        $this->used_by->add($character);
        $character->addGadget($this);
        return $this;
    }
    public function removeUsedBy(Character $character) : self
    {
        $this->used_by->removeElement($character);
        $character->removeGadget($this);
        return $this;
    }
    public function getCases() : Collection
    {
        return $this->cases;
    }
    public function addCase(CaseEntity $case) : self
    {
        $this->cases[] = $case;
        return $this;
    }
    public function removeCase(CaseEntity $case) : self
    {
        $this->cases->removeElement($case);
        return $this;
    }
}

templates/characters/appearances.html.twig
{% extends "base.html.twig" %}

{% block title %}Apparitions de {{ character }}{% endblock %}
{% block content %}
    {% if cases|length %}
        <div class="table-responsive">
            <table class="table cases">
                <thead>
                    <tr>
                        <th class="text-center column-id">#</th>
                        <th>Titre</th>
                        <th class="text-center">Manga</th>
                        <th class="text-center">Anime</th>
                        <th class="text-center">Intrigue</th>
                    </tr>
                </thead>
                <tbody>
                    {% for case in cases %}
                        {% include 'helper/case-row.html.twig' %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p><em>Aucun résultat trouvé.</em></p>
    {% endif %}
    <p class="text-center"><a href="{{ get_character_path(character) }}" class="btn btn-primary">Revenir à la fiche personnage</a></p>
{% endblock %}

templates/characters/gadget-uses.html.twig
{% extends "base.html.twig" %}

{% block title %}Utilisations du gadget {{ gadget.displayName }}{% endblock %}
{% block content %}
    {% if cases|length %}
        <div class="table-responsive">
            <table class="table cases">
                <thead>
                    <tr>
                        <th class="text-center column-id">#</th>
                        <th>Titre</th>
                        <th class="text-center">Manga</th>
                        <th class="text-center">Anime</th>
                        <th class="text-center">Intrigue</th>
                    </tr>
                </thead>
                <tbody>
                    {% for case in cases %}
                        {% include 'helper/case-row.html.twig' %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p><em>Aucun résultat trouvé.</em></p>
    {% endif %}
    <p class="text-center"><a href="{{ get_gadget_path(gadget) }}" class="btn btn-primary">Revenir à la fiche gadget</a></p>
{% endblock %}

templates/characters/gadget-view.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ gadget.displayName }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-8 order-2 order-md-1">
            <h3>{{ gadget.displayName }}</h3>

            {{ gadget.shortdesc|markdown_to_html }}
        </div>
        <div class="col-md-4 order-1 order-md-2">
            <div class="table-responsive">
                <table class="table profile_table gadget">
                    <thead>
                        <tr class="caption">
                            <th colspan="2">{{ gadget.displayName }} <a href="{{ path('admin_submission_edit', {'section': 'gadgets', 'id': gadget.id}) }}"><i class="far fa-edit text-white"></i></a></th>
                        </tr>
                        <tr>
                            <th class="p-0 text-center" colspan="2">
                                <a href="{{ asset('/img/gadget/' ~ gadget.id ~ '.jpg') }}">
                                    <img class="img-fluid" src="{{ asset('/img/gadget/' ~ gadget.id ~ '.jpg') }}" alt="" />
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="caption">
                            <th colspan="2">Informations</th>
                        </tr>
                        <tr>
                            <th>Nom français</th>
                            <td>{{ gadget.completeNameFr }}</td>
                        </tr>
                        <tr>
                            <th>Nom japonais</th>
                            <td>{{ gadget.nameJp }}</td>
                        </tr>
                        <tr>
                            <th>Créé par</th>
                            <td>{% if gadget.createdBy is not null %}<a href="{{ get_character_path(gadget.createdBy) }}">{{ gadget.createdBy }}</a>{% else %}Inconnu{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Utilisé par</th>
                            <td>
                                {% if gadget.usedBy|length %}
                                    {% for character in gadget.usedBy %}
                                        <a href="{{ get_character_path(character) }}">{{ character.fullname }}</a><br />
                                    {% endfor %}
                                {% endif %}
                            </td>
                        </tr>
                        <tr class="caption">
                            <th colspan="2">Statistiques</th>
                        </tr>
                        <tr>
                            <th>Première utilisation</th>
                            <td><a href="{{ get_case_path(gadget.firstUse) }}">{{ gadget.firstUse.displayName('long') }}</a></td>
                        </tr>
                        <tr>
                            <th>Utilisations</th>
                            <td><a href="{{ path('gadget_uses', {'id': gadget.id}) }}">{{ gadget.cases|length }}</a></td>
                        </tr>
                        <tr>
                            <td colspan="2" class="text-center"><a href="{{ path('gadgets') }}">Revenir à la liste des gadgets</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/characters/gadgets.html.twig
{% extends "base.html.twig" %}

{% block title %}Gadgets{% endblock %}
{% block content %}
    <p>Les gadgets sont principalement des outils inventés par le professeur Agasa pour aider Conan ou/et les Détectives Junior à résoudre les affaires, ou des outils utilisés par Kaitō Kid. On ne sait pas qui est l’auteur des gadgets de Kaitō Kid mais l’épisode 2 de Magic Kaito 1412 laisse penser qu’il s’agit du professeur Agasa en montrant une voiture jaune.</p>
    <hr />
    {% for character, gadgets in gadgets %}
        <h3>{{ character }}</h3>
        <div class="table-responsive table-gadgets">
            <table class="table">
                <thead>
                    <tr>
                        <th class="text-center">Image</th>
                        <th class="text-center">Nom</th>
                        <th class="text-center">Utilisé par</th>
                        <th class="text-center">Première utilisation</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for gadget in gadgets %}
                        <tr id="g{{ gadget.id }}">
                            <td class="align-middle text-center p-0"><img alt="" src="{{ asset('/img/gadget/' ~ gadget.id ~ '_60px.jpg') }}" height="60" width="60" /></td>
                            <td class="align-middle text-center"><a href="{{ get_gadget_path(gadget) }}">{{ gadget.displayName }}</a> <a href="{{ path('admin_submission_edit', {'section': 'gadgets', 'id': gadget.id}) }}"><i class="far fa-edit"></i></a></td>
                            <td class="align-middle text-center">
                                {% if gadget.usedBy|length %}
                                    {% for character in gadget.usedBy %}
                                        <a href="{{ get_character_path(character) }}">{{ character.fullname }}</a><br />
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td class="align-middle text-center"><a href="{{ get_case_path(gadget.firstUse) }}">{{ gadget.firstUse.displayName('long') }}</a></td>
                            <td class="align-middle markdown">{{ gadget.shortdesc|markdown_to_html }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <hr />
    {% endfor %}
    <p class="text-center"><a href="{{ path('admin_submission_add', {'section': 'gadgets'}) }}" class="btn btn-primary">Ajouter un gadget</a></p>
{% endblock %}

templates/characters/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Personnages{% endblock %}
{% block content %}
    <div class="alert alert-warning">Cet article contient des révélations importantes sur les identités secrètes et les intentions de certains personnages. Ces informations te seront probablement divulgâchées si tu n’as pas lu tous les chapitres publiés à ce jour.</div>
    <div class="row">
        <div class="col-lg-6 text-center"><img class="img-fluid" alt="" src="{{ asset('/img/character/all.jpg') }}" /></div>
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title text-center mb-0">Sommaire</h5></div>
                <div class="card-body">
                    {% import 'helper/menu-links.html.twig' as menus %}
                    {{ menus.menu_links(menu_items, 0) }}
                </div>
            </div>
        </div>
    </div>
    <hr />
    {% for char_cat in char_categories %}
        {% set level = 5 %}
        {% if char_cat.parent is null %}
            {% set level = 3 %}
        {% elseif char_cat.parent.parent is null %}
            {% set level = 4 %}
        {% endif %}
        <h{{ level }} id="cat{{ char_cat.id }}">{{ char_cat.name }}</h{{ level }}>
        {% if char_cat.characters|length %}
            <div class="table-responsive">
                <table class="table table-characters">
                    <thead>
                        <tr>
                            <th class="text-center">Image</th>
                            <th class="text-center">Nom</th>
                            <th>Rôle dans la série</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for character in char_cat.characters %}
                            <tr id="{{ character.shortname }}">
                                <td class="text-center align-middle p-0"><img alt="" src="{{ asset('/img/character/' ~ character.shortname ~ '_60px.jpg') }}" height="60" width="60" /></td>
                                <td class="text-center align-middle"><a href="{{ get_character_path(character) }}">{% include "helper/character-fullname.html.twig" with { 'character': character, 'newline': true } only %}</a> <a href="{{ path('admin_submission_edit', {'section': 'characters', 'id': character.id}) }}"><i class="far fa-edit"></i></a></td>
                                <td class="align-middle markdown">{{ character.shortdesc|markdown_to_html }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
        <hr />
    {% endfor %}
    <p class="text-center"><a href="{{ path('admin_submission_add', {'section': 'characters'}) }}" class="btn btn-primary">Ajouter un personnage</a></p>
{% endblock %}

templates/characters/view.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ character }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-8 order-2 order-md-1">
            <h3>{{ character }}</h3>

            {{ character.shortdesc|markdown_to_html }}
            <hr />

            {{ character.desc|markdown_to_html }}
        </div>
        <div class="col-md-4 order-1 order-md-2">
            <div class="table-responsive">
                <table class="table profile_table character">
                    <thead>
                        <tr class="caption">
                            <th colspan="2">{{ character }} <a href="{{ path('admin_submission_edit', {'section': 'characters', 'id': character.id}) }}"><i class="far fa-edit text-white"></i></a></th>
                        </tr>
                        <tr>
                            <th class="p-0 text-center" colspan="2">
                                <a href="{{ asset('/img/character/' ~ character.shortname ~ '.jpg') }}">
                                    <img class="img-fluid" src="{{ asset('/img/character/' ~ character.shortname ~ '.jpg') }}" alt="" />
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="caption">
                            <th colspan="2">Profil</th>
                        </tr>
                        <tr>
                            <th>Nom</th>
                            <td>{{ character.lastname }}{% if character.firstname is not null and character.firstname is not empty %} {{ character.firstname }}{% endif %}</td>
                        </tr>
                        {% if character.aliases is not null and character.aliases is not empty %}
                            <tr>
                                <th>Alias</th>
                                <td>{{ character.aliases }}</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <th>Genre</th>
                            <td>{{ genders[character.gender] }}</td>
                        </tr>
                        {% if character.age is not null and character.age is not empty and character.age != 0 %}
                            <tr>
                                <th>Âge</th>
                                <td>{{ character.age }} an{% if character.age > 1 %}s{% endif %}</td>
                            </tr>
                        {% endif %}
                        {% if character.height is not null and character.height is not empty and character.height != 0 %}
                            <tr>
                                <th>Taille</th>
                                <td>{{ character.height }} cm</td>
                            </tr>
                        {% endif %}
                        {% if character.weight is not null and character.weight is not empty and character.weight != 0 %}
                            <tr>
                                <th>Poids</th>
                                <td>{{ character.weight }} kg</td>
                            </tr>
                        {% endif %}
                        {% if character.occupation is not null and character.occupation is not empty %}
                            <tr>
                                <th>Métier</th>
                                <td>{{ character.occupation }}</td>
                            </tr>
                        {% endif %}
                        <tr class="caption">
                            <th colspan="2">Statistiques</th>
                        </tr>
                        <tr>
                            <th>Première apparition</th>
                            <td>{% if character.firstAppearance is not null %}<a href="{{ get_case_path(character.firstAppearance) }}">{{ character.firstAppearance.displayName('long') }}</a>{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Apparitions</th>
                            <td><a href="{{ path('character_appearances', {'shortname': character.shortname}) }}">{{ character.cases|length }}</a></td>
                        </tr>
                        <tr class="caption">
                            <th colspan="2">Acteurs</th>
                        </tr>
                        <tr>
                            <th>Voix japonaise</th>
                            <td>{{ character.voiceJp }}</td>
                        </tr>
                        {% if character.voiceFr is not null and character.voiceFr is not empty %}
                        <tr>
                            <th>Voix française</th>
                            <td>{{ character.voiceFr }}</td>
                        </tr>
                        {% endif %}
                        <tr>
                            <td colspan="2" class="text-center"><a href="{{ path('characters') }}">Revenir à la liste des personnages</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}